project:
  type: website
  output-dir: docs

website:
  title: "Workbook Bio Data Science"
  site-url: https://jkruppa.github.io/workbook/
  description: 'Inspired by the saying "An apple a day keeps the doctor away", this project titled "A Quarto tip a day keeps the docs away" is a playful attempt to share Quarto tips for a month leading up to my rstudio::conf(2022) keynote on Quarto.'
  repo-url: https://github.com/jkruppa/workbook
  repo-actions: [edit, issue]  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:
    left: |
      Workbook Bio Data Science wurde von <a href="https://www.hs-osnabrueck.de/prof-dr-jochen-kruppa/">Jochen Kruppa-Scheetz</a> geschrieben. 
    right: |
      Dieses Workbook wurde mit <a href="https://quarto.org/">Quarto</a> erstellt.

format:
  html:
    author: "<a href='https://www.hs-osnabrueck.de/prof-dr-jochen-kruppa/'>Prof. Dr. Jochen Kruppa-Scheetz</a>"
    theme:
      light: [simplex]
      dark: [darkly]
    highlight-style: tango
    code-copy: true
    code-overflow: wrap
    toc: true
    code-annotations: hover
    lightbox: true
    toc-expand: 2
    code-fold: show
    code-block-border-left: true
    code-summary: "R Code [zeigen / verbergen]"
    code-tools: true


